-- MOBIQ ERP: Datenbankstand Release 26.2.
-- Ab hier führen die Flyway-Migrationen aus db/migration im Repository (V26_3_*, V26_4_*) weiter.
-- PostgreSQL 18

CREATE TABLE filiale (
  filial_id  serial       PRIMARY KEY,
  name       varchar(80)  NOT NULL,
  ort        varchar(60)  NOT NULL,
  plz        char(5)      NOT NULL
);

CREATE TABLE kunde (
  kunde_id   bigserial    PRIMARY KEY,
  kunde_nr   varchar(10)  NOT NULL UNIQUE,
  vorname    varchar(60)  NOT NULL,
  nachname   varchar(60)  NOT NULL,
  strasse    varchar(80),
  plz        char(5),
  ort        varchar(60),
  email      varchar(120),
  angelegt   date         NOT NULL
);

CREATE TABLE artikel (
  artikel_nr   varchar(10)   PRIMARY KEY,
  bezeichnung  varchar(120)  NOT NULL,
  warengruppe  varchar(40)   NOT NULL,
  preis        numeric(10,2) NOT NULL CHECK (preis >= 0),
  gewicht_kg   numeric(7,2),
  volumen_m3   numeric(6,3)
);

CREATE TABLE fahrzeug (
  fahrzeug_id    serial       PRIMARY KEY,
  kennzeichen    varchar(12)  NOT NULL UNIQUE,
  bezeichnung    varchar(60)  NOT NULL,
  ladevolumen_m3 numeric(5,1) NOT NULL,
  filial_id      integer      NOT NULL REFERENCES filiale (filial_id)
);

CREATE TABLE kaufvertrag (
  kv_id         bigserial     PRIMARY KEY,
  kv_nr         varchar(12)   NOT NULL UNIQUE,
  kunde_id      bigint        NOT NULL REFERENCES kunde (kunde_id),
  filial_id     integer       NOT NULL REFERENCES filiale (filial_id),
  status        varchar(20)   NOT NULL DEFAULT 'ERFASST'
                CHECK (status IN ('ERFASST','LIEFERBEREIT','DISPONIERT','AUSGELIEFERT','ABGERECHNET','STORNIERT')),
  anzahlung     numeric(10,2) NOT NULL DEFAULT 0,
  liefersperre  boolean       NOT NULL DEFAULT false,
  erfasst_am    date          NOT NULL,
  wunschtermin  date
);

CREATE TABLE kv_position (
  kvp_id       bigserial     PRIMARY KEY,
  kv_id        bigint        NOT NULL REFERENCES kaufvertrag (kv_id),
  pos_nr       smallint      NOT NULL,
  artikel_nr   varchar(10)   NOT NULL REFERENCES artikel (artikel_nr),
  menge        integer       NOT NULL CHECK (menge > 0),
  einzelpreis  numeric(10,2) NOT NULL,
  im_lager     boolean       NOT NULL DEFAULT false,
  UNIQUE (kv_id, pos_nr)
);

CREATE TABLE tour (
  tour_id      bigserial    PRIMARY KEY,
  tour_datum   date         NOT NULL,
  fahrzeug_id  integer      NOT NULL REFERENCES fahrzeug (fahrzeug_id),
  fahrer       varchar(60)  NOT NULL
);

CREATE TABLE tour_stopp (
  stopp_id     bigserial    PRIMARY KEY,
  tour_id      bigint       NOT NULL REFERENCES tour (tour_id),
  kv_id        bigint       NOT NULL REFERENCES kaufvertrag (kv_id),
  reihenfolge  smallint     NOT NULL,
  avisiert_am  timestamp,
  UNIQUE (tour_id, reihenfolge)
);

-- Kassenbelege: der Primärschlüssel enthält das Belegdatum, damit die Tabelle später nach Jahr
-- partitioniert werden kann (V26_4_015). Eine Partition kann nicht per Fremdschlüssel angesprochen werden,
-- darum verweist kassenzahlung nur über Beleg und Datum, ohne Constraint.
CREATE TABLE kassenbeleg (
  beleg_id    bigint GENERATED BY DEFAULT AS IDENTITY,
  belegdatum  date          NOT NULL,
  filial_id   integer       NOT NULL REFERENCES filiale (filial_id),
  kasse_nr    smallint      NOT NULL,
  summe       numeric(10,2) NOT NULL,
  storniert   boolean       NOT NULL DEFAULT false,
  PRIMARY KEY (beleg_id, belegdatum)
);
CREATE INDEX idx_kassenbeleg_tag ON kassenbeleg (filial_id, belegdatum);

CREATE TABLE gutschein (
  gutschein_nr  varchar(14)   PRIMARY KEY,
  wert          numeric(10,2) NOT NULL,
  restwert      numeric(10,2) NOT NULL CHECK (restwert >= 0),
  ausgestellt   date          NOT NULL,
  gueltig_bis   date          NOT NULL
);

CREATE TABLE kassenzahlung (
  zahlung_id    bigserial     PRIMARY KEY,
  beleg_id      bigint        NOT NULL,
  belegdatum    date          NOT NULL,
  zahlart       varchar(10)   NOT NULL CHECK (zahlart IN ('BAR','KARTE','GUTSCHEIN')),
  betrag        numeric(10,2) NOT NULL,
  gutschein_nr  varchar(14)   REFERENCES gutschein (gutschein_nr)
);

CREATE TABLE rechnung (
  rechnung_id  bigserial     PRIMARY KEY,
  rechnungs_nr varchar(14)   NOT NULL UNIQUE,
  kv_id        bigint        NOT NULL REFERENCES kaufvertrag (kv_id),
  belegart     char(2)       NOT NULL,
  betrag       numeric(10,2) NOT NULL,
  belegdatum   date          NOT NULL
);

-- Flyway merkt sich hier, welche Migrationen gelaufen sind.
CREATE TABLE flyway_schema_history (
  installed_rank  integer       PRIMARY KEY,
  version         varchar(50),
  description     varchar(200)  NOT NULL,
  type            varchar(20)   NOT NULL,
  script          varchar(1000) NOT NULL,
  checksum        integer,
  installed_by    varchar(100)  NOT NULL,
  installed_on    timestamp     NOT NULL,
  execution_time  integer       NOT NULL,
  success         boolean       NOT NULL
);
